### ISSUE TITLE
Shared Flux generates different values

### ISSUE THREAD

**Issue by fmacicasan** [bclozel/webflux-streaming-showcase#2]
Hello!

Thanks for the great example!

I'm playing with the QuoteStream Application and i opened two "**http get :8081/quotes --stream**" that generate different values.

Shouldn't the "**.share()**" from the QuoteGenerator Flux make both streams output the same values?

**Comment by bclozel** [comment]
I've updated the handler to instantiate one `Flux<Quote>` and use the `share()` operator on it - this instance is then kept as an attribute. Previously that `Flux` was being re-created for every request, which defeated the goal of the `share` operator.

This is now fixed. Thanks!
